# import OSC functions
import time
from osc4py3.as_eventloop import * # needed to send and receive OSC
from osc4py3 import oscbuildparse # needed to send OSC
from osc4py3 import oscmethod as osm # needed to receive OSC

fundamental = 100
mode = 0
transposition = 0
intevalA = 5 / 2
intervalB = 7 / 4
generator_interval = min(intevalA, intervalB)   # interval to stack
cycle_interval = max(intevalA, intervalB)       # limit for stacked intervals (pseudo-octave)
pseudo_octave = 0
transpositionDegree = 0
transpositionDegreeDirection = None
degreeDirection = None
transpositionDirection = "up"
notesNumber = 5
frequencies = []
genTransp_interval = 1

# DEFINE FUNCTIONS
# function to calculate frequencies
def calculateFreqs():
    # storage vector for frecuencies
    global frequencies
    frequencies = []
    # test whether the selected mode is within boundaries
    if 0 <= mode < notesNumber:
        # store fundamental as first element
        frequency = fundamental
        frequencies.append(frequency)

        # CALCULATE FREQUENCIES
        # based on the mode, calculate the frequencies based
        # on the generator interval down from the fundamental
        # and put them within the cycle interval boundaries
        for x in range(notesNumber - mode - 1):
            frequency *= generator_interval
            while frequency > fundamental * cycle_interval:
                frequency /= cycle_interval
            frequencies.append(frequency)
        # same as above but for the frequencies generated by
        # the generator interval going up
        frequency = fundamental
        for x in range(mode):
            frequency /= generator_interval
            while frequency < fundamental:
                frequency *= cycle_interval
            frequencies.append(frequency)

        # duplicate scale over cycle interval
        for x in range(notesNumber):
            frequencies.append(frequencies[x] * cycle_interval)

        # add last note (2 cycle intervals above fundamental)
        frequencies.append(frequencies[0] * cycle_interval ** 2)

        # transposition by cycle interval
        if pseudo_octave == -1:
            frequencies = [x / cycle_interval for x in frequencies]
        if pseudo_octave == 1:
            frequencies = [x * cycle_interval for x in frequencies]

        # transposition by generator interval
        frequencies = [x * genTransp_interval for x in frequencies]

        # sort intervals
        frequencies.sort()

    else:
        print("false mode number!")

# send frequencies through OSC
def sendFreqs():
    osc_send(oscbuildparse.OSCMessage(
        '/freqs', ',fffffffffff', frequencies
    ),'scOSCClient')

# define mode cycle function
def cycleModes(modeDirection):
    global mode, frequencies

    # previouus mode
    print(f"mode change: {modeDirection}")
    if modeDirection == "prev":
        if mode > 0:
            mode -= 1
            calculateFreqs()
    # next mode
    if modeDirection == "next":
        if mode < notesNumber - 1:
            mode += 1
            calculateFreqs()
    
    # send new frequencies
    sendFreqs()
    
    freqsRounded = [round(x, 2) for x in frequencies]
    print(
        f"current mode: {mode + 1}/{notesNumber}\n"
        f"frequencies: {freqsRounded}\n"
    )

# define cycle interval transpose function
def cycle_intervalTranspose(cycle_intervalTranspDir):
    global frequencies, pseudo_octave

    # transpose down by cycle interval
    print(f"transposition by cycle interval: {cycle_intervalTranspDir}")
    if cycle_intervalTranspDir == "down":
        if pseudo_octave > -1:
            pseudo_octave -= 1
            calculateFreqs()
    # transpose up by cycle interval
    if cycle_intervalTranspDir == "up":
        if pseudo_octave < 1:
            pseudo_octave += 1
            calculateFreqs()
    
    # send new frequencies
    sendFreqs()

    freqsRounded = [round(x, 2) for x in frequencies]
    print(
        f"current pseudo-octave: {pseudo_octave + 1}\n"
        f"frequencies: {freqsRounded}\n"
    )

# define generator interval transpose function
def generator_intervalTranspose(address, message):
    global frequencies, transpositionDegree, transpositionDegreeDirection
    global degreeDirection, transpositionDirection, genTransp_interval

    if address == "/transposition/generator_interval/degreeDirection":
        degreeDirection = message
    if address == "/transposition/generator_interval/transpositionDirection":
        transpositionDirection = message
        print(f"transposition direction set to: {transpositionDirection}")

    # evaluate frequencies transposed down a degree if selected direction matches
    if degreeDirection == "down":
        print("degree direction: down")
        if transpositionDirection == "down":
            print("transposition direction: down")
            # perform calculation "down down" if new degree falls within boundaries
            if transpositionDegree > -(notesNumber - 1):
                # reduce transposition degree by 1
                transpositionDegree -= 1
                # divide scale "fundamental" by generator interval
                genTransp_interval = genTransp_interval / generator_interval
                # multiply frequency by cyle interval if it goes below it
                if genTransp_interval <= 1 / cycle_interval:
                    genTransp_interval = genTransp_interval * cycle_interval
        if transpositionDirection == "up":
            print("transposition direction: up")
            # perform calculation "down up" if new degree falls within boundaries
            if  transpositionDegree > -(notesNumber - 1):
                # reduce transposition degree by 1
                transpositionDegree -= 1
                # divide scale "fundamental" by generator interval
                genTransp_interval = genTransp_interval / generator_interval
                # multiply frequency by cyle interval if it goes below scale "fundamental"
                if genTransp_interval < 1:
                    genTransp_interval = genTransp_interval * cycle_interval
    
    # evaluate frequencies transposed up a degree if selected direction matches
    if degreeDirection == "up":
        print("degree direction: up")
        if transpositionDirection == "down":
            print("transposition direction: down")
            # perform calculation "up down" if new degree falls within boundaries
            if transpositionDegree < (notesNumber - 1):
                # increment transposition degree by 1
                transpositionDegree += 1
                # multiply scale "fundamental" by generator interval
                genTransp_interval = genTransp_interval * generator_interval
                # divide frequency by cyle interval if it falls above scale "fundamental"
                if genTransp_interval > 1:
                    genTransp_interval = genTransp_interval / cycle_interval
        if transpositionDirection == "up":
            print("transposition direction: up")
            if transpositionDegree < (notesNumber - 1):
                # increment transposition degree by 1
                transpositionDegree += 1
                # multiply scale "fundamental" by generator interval
                genTransp_interval = genTransp_interval * generator_interval
                # divide frequency by cyle interval if it goes above it
                if genTransp_interval >= cycle_interval:
                    genTransp_interval = genTransp_interval / cycle_interval

    if genTransp_interval < 1:
        transpositionDegreeDirection = "down"
    elif genTransp_interval > 1:
        transpositionDegreeDirection = "up"

    if address == "/transposition/generator_interval/degreeDirection":
        # calculate and send new frequencies
        calculateFreqs()
        sendFreqs()

        # print transposition information and new frequencies
        if transpositionDegree == 0:
            print(f"current degree: {transpositionDegree}")
        else:
            print(f"current degree: {transpositionDegree} {transpositionDegreeDirection}")
        print(genTransp_interval)
        freqsRounded = [round(x, 2) for x in frequencies]
        print(f"frequencies: {freqsRounded}\n")
    
    degreeDirection = None
    print("")
                



# === === # === === # === === # === === # === === # === === #

# start OSC 
osc_startup()
# set up client to send messages
osc_udp_client('127.0.0.1', 57120, 'scOSCClient')
print("OSC Client started. Ready to send messages!")
# set up OSC server to receive messages
osc_udp_server("127.0.0.1", 57121, 'scOSCServer')
print("OSC Server started. Ready to receive messages!")

# calculate and send initial frequencies
calculateFreqs()
sendFreqs()
print(frequencies, "\n")

# osc method to call cycleModes function
osc_method("/mode", cycleModes)

# osc method to call transposition by cycle interval function
osc_method("/transposition/cycle_interval", cycle_intervalTranspose)

# osc method to call transposition by generator interfal fuanction
osc_method(
    "/transposition/generator_interval",
    generator_intervalTranspose,
    argscheme=osm.OSCARG_ADDRESS + osm.OSCARG_DATAUNPACK
)


finished = False
try:
    while True:
        osc_process()
        time.sleep(0.001)
except KeyboardInterrupt:
    osc_terminate()
