from fractions import Fraction
from osc4py3.as_eventloop import * # needed to send and receive OSC
from osc4py3 import oscbuildparse # needed to send OSC
from osc4py3 import oscmethod as osm # needed to receive OSC

class Frequencies:
    def __init__(self):
        self.oscAddress = None
        self.fundamental = 100
        self.mode = 0
        self.transposition = 0
        self.intervalA = Fraction(5/2)
        self.intervalB = Fraction(7/4)
        self.generator_interval = min(self.intervalA, self.intervalB)   # interval to stack
        self.cycle_interval = max(self.intervalA, self.intervalB)       # limit for stacked intervals (pseudo-octave)
        self.pseudo_octave = 0
        self.transpositionDegree = 0
        self.transpositionDegreeDirection = None
        self.degreeDirection = None
        self.transpositionDirection = "up"
        self.notesNumber = 5
        self.frequencies = []
        self.genTransp_interval = 1
    
    _active_instances = {}
    _registered_addresses = set()

    def startup(self, instanceAddress):
    # calculate and send initial frequencies
        self.oscAddress = instanceAddress
        Frequencies._active_instances[self.oscAddress] = self
        self.calculateFreqs()
        self.sendFreqs()
        freqsRounded = [round(float(x), 2) for x in self.frequencies]

        if self.oscAddress not in Frequencies._registered_addresses:
            addr = self.oscAddress

            def mode_wrapper(modeDirection):
                inst = Frequencies._active_instances.get(addr)
                if inst:
                    inst.cycleModes(modeDirection)

            def cycle_wrapper(direction):
                inst = Frequencies._active_instances.get(addr)
                if inst:
                    inst.cycle_intervalTranspose(direction)

            def gen_wrapper(address, message):
                inst = Frequencies._active_instances.get(addr)
                if inst:
                    inst.generator_intervalTranspose(address, message)    

            # osc method to call cycleModes function
            osc_method(self.oscAddress + "/mode", mode_wrapper)

            # osc method to call transposition by cycle interval function
            osc_method(self.oscAddress + "/transposition/cycle_interval", cycle_wrapper)

            # osc method to call transposition by generator interfal fuanction
            osc_method(
                self.oscAddress + "/transposition/generator_interval",
                gen_wrapper,
                argscheme=osm.OSCARG_ADDRESS + osm.OSCARG_DATAUNPACK
            )

            Frequencies._registered_addresses.add(self.oscAddress)

        return self

    def calculateFreqs(self):
        self.frequencies = []
        # test whether the selected mode is within boundaries
        if 0 <= self.mode < self.notesNumber:
            # store fundamental as first element
            frequency = self.fundamental
            self.frequencies.append(frequency)

            # CALCULATE FREQUENCIES
            # based on the mode, calculate the frequencies based
            # on the generator interval down from the fundamental
            # and put them within the cycle interval boundaries
            for x in range(self.notesNumber - self.mode - 1):
                frequency *= self.generator_interval
                while frequency > self.fundamental * self.cycle_interval:
                    frequency /= self.cycle_interval
                self.frequencies.append(frequency)
            # same as above but for the frequencies generated by
            # the generator interval going up
            frequency = self.fundamental
            for x in range(self.mode):
                frequency /= self.generator_interval
                while frequency < self.fundamental:
                    frequency *= self.cycle_interval
                self.frequencies.append(frequency)

            # duplicate scale over cycle interval
            for x in range(self.notesNumber):
                self.frequencies.append(self.frequencies[x] * self.cycle_interval)

            # add last note (2 cycle intervals above fundamental)
            self.frequencies.append(self.frequencies[0] * self.cycle_interval ** 2)

            # transposition by cycle interval
            if self.pseudo_octave == -1:
                self.frequencies = [x / self.cycle_interval for x in self.frequencies]
            if self.pseudo_octave == 1:
                self.frequencies = [x * self.cycle_interval for x in self.frequencies]

            # transposition by generator interval
            self.frequencies = [x * self.genTransp_interval for x in self.frequencies]

            # sort intervals
            self.frequencies.sort()

        else:
            print("false mode number!")

    # send frequencies through OSC
    def sendFreqs(self):
        osc_send(oscbuildparse.OSCMessage(
            self.oscAddress, ',fffffffffff', self.frequencies
        ),'scOSCClient')

    # define mode cycle function
    def cycleModes(self, modeDirection):

        # previouus mode
        print(f"mode change: {modeDirection}")
        if modeDirection == "prev":
            if self.mode > 0:
                self.mode -= 1
                self.calculateFreqs()
        # next mode
        if modeDirection == "next":
            if self.mode < self.notesNumber - 1:
                self.mode += 1
                self.calculateFreqs()

        # send new frequencies
        self.sendFreqs()

        freqsRounded = [round(float(x), 2) for x in self.frequencies]
        print(
            f"current mode: {self.mode + 1}/{self.notesNumber}\n"
            f"frequencies: {freqsRounded}\n"
        )

    # define cycle interval transpose function
    def cycle_intervalTranspose(self, cycle_intervalTranspDir):

        # transpose down by cycle interval
        print(f"transposition by cycle interval: {cycle_intervalTranspDir}")
        if cycle_intervalTranspDir == "down":
            if self.pseudo_octave > -1:
                self.pseudo_octave -= 1
                self.calculateFreqs()
        # transpose up by cycle interval
        if cycle_intervalTranspDir == "up":
            if self.pseudo_octave < 1:
                self.pseudo_octave += 1
                self.calculateFreqs()

        # send new frequencies
        self.sendFreqs()

        freqsRounded = [round(float(x), 2) for x in self.frequencies]
        print(
            f"current pseudo-octave: {self.pseudo_octave + 1}\n"
            f"frequencies: {freqsRounded}\n"
        )

    # define generator interval transpose function
    def generator_intervalTranspose(self, address, message):

        if address == self.oscAddress + "/transposition/generator_interval/degreeDirection":
            self.degreeDirection = message
        if address == self.oscAddress + "/transposition/generator_interval/transpositionDirection":
            self.transpositionDirection = message
            print(f"transposition direction set to: {self.transpositionDirection}")

        # evaluate frequencies transposed down a degree if selected direction matches
        if self.degreeDirection == "down":
            print("degree direction: down")
            if self.transpositionDirection == "down":
                print("transposition direction: down")
                # perform calculation "down down" if new degree falls within boundaries
                if self.transpositionDegree > -(self.notesNumber - 1):
                    # reduce transposition degree by 1
                    self.transpositionDegree -= 1
                    # divide scale "fundamental" by generator interval
                    self.genTransp_interval = self.genTransp_interval / self.generator_interval
                    # multiply frequency by cyle interval if it goes below it
                    if self.genTransp_interval <= 1 / self.cycle_interval:
                        self.genTransp_interval = self.genTransp_interval * self.cycle_interval
            if self.transpositionDirection == "up":
                print("transposition direction: up")
                # perform calculation "down up" if new degree falls within boundaries
                if self.transpositionDegree > -(self.notesNumber - 1):
                    # reduce transposition degree by 1
                    self.transpositionDegree -= 1
                    # divide scale "fundamental" by generator interval
                    self.genTransp_interval = self.genTransp_interval / self.generator_interval
                    # multiply frequency by cyle interval if it goes below scale "fundamental"
                    if self.genTransp_interval < 1:
                        self.genTransp_interval = self.genTransp_interval * self.cycle_interval

        # evaluate frequencies transposed up a degree if selected direction matches
        if self.degreeDirection == "up":
            print("degree direction: up")
            if self.transpositionDirection == "down":
                print("transposition direction: down")
                # perform calculation "up down" if new degree falls within boundaries
                if self.transpositionDegree < (self.notesNumber - 1):
                    # increment transposition degree by 1
                    self.transpositionDegree += 1
                    # multiply scale "fundamental" by generator interval
                    self.genTransp_interval = self.genTransp_interval * self.generator_interval
                    # divide frequency by cyle interval if it falls above scale "fundamental"
                    if self.genTransp_interval > 1:
                        self.genTransp_interval = self.genTransp_interval / self.cycle_interval
            if self.transpositionDirection == "up":
                print("transposition direction: up")
                if self.transpositionDegree < (self.notesNumber - 1):
                    # increment transposition degree by 1
                    self.transpositionDegree += 1
                    # multiply scale "fundamental" by generator interval
                    self.genTransp_interval = self.genTransp_interval * self.generator_interval
                    # divide frequency by cyle interval if it goes above it
                    if self.genTransp_interval >= self.cycle_interval:
                        self.genTransp_interval = self.genTransp_interval / self.cycle_interval

        if self.genTransp_interval < 1:
            self.transpositionDegreeDirection = "down"
        elif self.genTransp_interval > 1:
            self.transpositionDegreeDirection = "up"

        if address == self.oscAddress + "/transposition/generator_interval/degreeDirection":
            # calculate and send new frequencies
            self.calculateFreqs()
            self.sendFreqs()

            # print transposition information and new frequencies
            if self.transpositionDegree == 0:
                print(f"current degree: {self.transpositionDegree}")
            else:
                print(f"current degree: {self.transpositionDegree} {self.transpositionDegreeDirection}")
            print(self.genTransp_interval)
            freqsRounded = [round(float(x), 2) for x in self.frequencies]
            print(f"frequencies: {freqsRounded}\n")

        self.degreeDirection = None
        print("")
